- name: Installed PHP Server
  yum:
    name: "{{ packages }}"
    state: present

- name: Configure PHP Server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop:
    - { src: php.ini.j2 , dest: /etc/php.ini , mode: '0644' } 
    - { src: php_www.conf.j2 , dest: /etc/php-fpm.d/www.conf , mode: '0644' } 
  notify: Restart PHP Server

- name: Systemd PHP Server
  systemd:
    name: php-fpm
    state: started
    enabled: yes

