- name: Import SSL Key
  copy:
    src: ssl_key
    dest: /etc/nginx/

- name: Create Nginx Proxy  VirtHost Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: proxy_params.j2 , dest: /etc/nginx/proxy_params }
    - { src: proxy_blog.oldxu.com.conf.j2 , dest: /etc/nginx/conf.d/proxy_blog.oldxu.com.conf }
  notify: Restart Nginx Server

